output "app_server_1_private_ip" { value = aws_instance.app_server_1.private_ip }
output "app_server_2_private_ip" { value = aws_instance.app_server_2.private_ip }
output "bastion_public_ip"       { value = aws_instance.bastion.public_ip }
output "jenkins_private_ip"      { value = aws_instance.jenkins.private_ip }
output "db_private_ip"           { value = aws_instance.db.private_ip }
output "rabbitmq_private_ip"     { value = aws_instance.rabbitmq.private_ip }
output "memcached_private_ip"    { value = aws_instance.memcached.private_ip }
output "app_instance_ids"        { value = [aws_instance.app_server_1.id, aws_instance.app_server_2.id] }
output "db_instance_id"          { value = aws_instance.db.id }
