# variable "project_name"           { type = string }
# variable "environment"             { type = string }
# variable "aws_region"              { type = string }
# variable "key_name"                { type = string }
# variable "app_subnet_id"           { type = string }
# variable "public_subnet_id"         { type = string }
# variable "data_subnet_id"          { type = string }
# variable "app_sg_id"               { type = string }
# variable "tools_sg_id"             { type = string }
# variable "db_sg_id"                { type = string }
# variable "bastion_sg_id"           { type = string }
# variable "app_instance_profile"    { type = string }
# variable "tools_instance_profile"  { type = string }
# variable "db_instance_profile"     { type = string }
# variable "alb_target_group_arn"    { type = string }
# variable "app_instance_type"       { type = string }
# variable "db_instance_type"        { type = string }
# variable "tools_instance_type"     { type = string }
variable "project_name"           { type = string }
variable "environment"             { type = string }
variable "aws_region"              { type = string }
variable "key_name"                { type = string }
variable "app_subnet_id"           { type = string }
variable "public_subnet_id"        { type = string }
variable "tools_subnet_id"         { type = string }
variable "data_subnet_id"          { type = string }
variable "app_sg_id"               { type = string }
variable "tools_sg_id"             { type = string }
variable "db_sg_id"                { type = string }
variable "bastion_sg_id"           { type = string }
variable "app_instance_profile"    { type = string }
variable "tools_instance_profile"  { type = string }
variable "db_instance_profile"     { type = string }
variable "alb_target_group_arn"    { type = string }
variable "app_instance_type"       { type = string }
variable "db_instance_type"        { type = string }
variable "tools_instance_type"     { type = string }