---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/enterprise-application-platform-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    app_servers:
      hosts:
        app-01:
          ansible_host: 10.0.2.99
        app-02:
          ansible_host: 10.0.2.6

    message_queue:
      hosts:
        rabbitmq-01:
          ansible_host: 10.0.2.117

    cache:
      hosts:
        memcached-01:
          ansible_host: 10.0.2.254

    tools:
      hosts:
        jenkins-01:
          ansible_host: 10.0.3.44

    database:
      hosts:
        db-01:
          ansible_host: 10.0.4.53
          ansible_user: ec2-user

