#!/usr/bin/env bash
# generate-inventory.sh — build the Ansible inventory from Terraform outputs.
#
# Private IPs change on every `terraform apply`, so they are not committed.
# Run this after each apply:   make inventory
#
# Ansible is run from the Bastion host (see docs/bastion-setup.md), so the
# hosts are addressed by their private IPs directly.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT_DIR}/terraform/environments/production"
OUT_FILE="${ROOT_DIR}/ansible/inventories/production/hosts.yml"

tf_out() {
  terraform -chdir="${TF_DIR}" output -raw "$1"
}

APP1="$(tf_out app_server_1_private_ip)"
APP2="$(tf_out app_server_2_private_ip)"
RABBITMQ="$(tf_out rabbitmq_private_ip)"
MEMCACHED="$(tf_out memcached_private_ip)"
JENKINS="$(tf_out jenkins_private_ip)"
DB="$(tf_out db_private_ip)"

cat > "${OUT_FILE}" <<EOF
---
# Generated by scripts/generate-inventory.sh — do not edit by hand.
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/enterprise-application-platform-key.pem

  children:
    app_servers:
      hosts:
        app-01:
          ansible_host: ${APP1}
        app-02:
          ansible_host: ${APP2}

    message_queue:
      hosts:
        rabbitmq-01:
          ansible_host: ${RABBITMQ}

    cache:
      hosts:
        memcached-01:
          ansible_host: ${MEMCACHED}

    tools:
      hosts:
        jenkins-01:
          ansible_host: ${JENKINS}

    database:
      hosts:
        db-01:
          ansible_host: ${DB}
          ansible_user: ec2-user
EOF

echo "Inventory written to ${OUT_FILE}"
